# =============================================
# PERFIL NEON - Prueba local con BD en la nube
# =============================================

spring.application.name=Sistema Botica

# --- PostgreSQL Neon ---
spring.datasource.url=jdbc:postgresql://ep-soft-wave-aqhj09gp-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Tpwe5KU7hNtQ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=5000

# --- JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.h2.console.enabled=false

# --- Thymeleaf ---
spring.thymeleaf.cache=false

# --- Subida de archivos (local) ---
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=./uploads/productos

# Cloudinary - almacenamiento persistente de imágenes
cloudinary.enabled=true
cloudinary.url=cloudinary://768998739822132:pSLEkQvYsTvBEiKaqSSuil9QcbQ@doysasp62

# --- Servidor ---
server.port=8080

# --- SUNAT beta ---
sunat.ruc=20000000001
sunat.razon-social=BOTICA SALUD S.A.C.
sunat.nombre-comercial=BOTICA SALUD
sunat.ubigeo=150101
sunat.direccion=AV. PRINCIPAL 123
sunat.urbanizacion=URB. LOS JARDINES
sunat.distrito=LIMA
sunat.provincia=LIMA
sunat.departamento=LIMA
sunat.usuario-sol=USUARIO_SOL_AQUI
sunat.clave-sol=CLAVE_SOL_AQUI
sunat.serie-factura=F001
sunat.serie-boleta=B001
sunat.url-beta=https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService
sunat.url-produccion=https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService
sunat.modo=beta

logging.level.com.botica=INFO
